# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  noutube = {
    pname = "noutube";
    version = "v0.3.1";
    src = fetchurl {
      url = "https://github.com/nonbili/NouTube-Desktop/releases/download/v0.3.1/linux-unpacked.zip";
      sha256 = "sha256-UIB7a9Dg9/Xt+PVNKn2pxGcfZPVYUnQL4NrZB+R0FhI=";
    };
  };
}
