# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  noutube = {
    pname = "noutube";
    version = "v0.3.0";
    src = fetchurl {
      url = "https://github.com/nonbili/NouTube-Desktop/releases/download/v0.3.0/linux-unpacked.zip";
      sha256 = "sha256-gBT2urUPZjnaM1hX08AqcIoZtR6yVkwfb25gK8FpDYI=";
    };
  };
}
